---
- name: brew
  hosts: all
  tasks:
    - name: copy Brewfile
      copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        force: yes
      loop:
        - {src: brew/Brewfile, dest: ~/Brewfile}
...
