---
# deps.edn は Homebrew のコピーに
# org.slf4j/slf4j-nop {:mvn/version "RELEASE"}
# を追加。
#
# * 2022-12-09: deps.edn to ~/.config/clojure/
#   antq がアップデートなって、org.slf4j/sl4j-nop の記述が不要になった？
- name: clojure, leiningen, cljstyle
  hosts: all
  tasks:
    - name: copy clojure/deps.edn into ~/.config/clojure
      copy:
        src: clojure/deps.edn
        dest: ~/.config/clojure/
        force: yes
    - name: copy clojure/profiles.clj into ~/.lein
      copy:
        src: clojure/profiles.clj
        dest: ~/.lein/
        force: yes
    - name: copy clojure/cljstyle to ~/.cljstyle
      copy:
        src: clojure/cljstyle
        dest: ~/.cljstyle
        force: yes
...
