---
- name: setup ~/.emacs.d
  hosts: all
  tasks:
    - name: exists ~/.emacs.d
      file:
        path: ~/.emacs.d
        state: directory
    - name: exists ~/.emacs.d/inits
      file:
        path: ~/.emacs.d/inits
        state: directory
    - name: exists ~/.emacs.d/inits-disabled
      file:
        path: ~/.emacs.d/inits-disabled
        state: directory
    - name: copy emacs/early-init.el into ~/.emacs.d/
      copy:
        src: emacs/early-init.el
        dest: ~/.emacs.d/
    - name: copy emacs/init.el into ~/.emacs.d/
      copy:
        src: emacs/init.el
        dest: ~/.emacs.d/
    - name: sync emacs/inits/ into ~/.emacs.d/inits/
      synchronize:
        src: emacs/inits/
        dest: ~/.emacs.d/inits/
        delete: yes
    - name: sync emacs/inits-disabled/ into ~/.emacs.d/inits-disabled/
      synchronize:
        src: emacs/inits-disabled/
        dest: ~/.emacs.d/inits-disabled/
        delete: yes
...
