---
# zshenv は自分で用意する。
- name: copy zsh init files.
  hosts: all
  tasks:
    - name: copy zprofile, zshrc, zsh_aliases.
      copy:
        src:  "{{item.src}}"
        dest: "{{item.dest}}"
        mode: "0600"
        force: yes
      loop:
        # - {src: zsh/zshenv,      dest: ~/.zshenv}
        - {src: zsh/zprofile,    dest: ~/.zprofile}
        - {src: zsh/zshrc,       dest: ~/.zshrc}
        - {src: zsh/zsh-aliases, dest: ~/.zsh_aliases}
    - name: prepare zshenv by yourself
      debug:
        msg: "Prepare zshenv by yourself.
              Github claims when finding a definition of GITHUB_API_TOKEN."
...

