#!/bin/zsh
#
# origin: ${dotfiles}/zsh/zprofile
#
# * set app specific paths, etc.
# * setup PATH.
# * read ~/.zsh_aliases.

########################
### this was in zshenv.

bindkey -e

export EDITOR=vi
export GIT_EDITOR=vi
export LANG=ja_JP.UTF-8
export TERM=xterm-256color
export VAGRANT_DEFAULT_PROVIDER=virtualbox

## do not include resouce fork in tar in macos.
export COPYFILE_DISABLE=1

## macos ruby special
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES

## https://www.rasukarusan.com/entry/2018/08/14/083000
export FZF_DEFAULT_OPTS='--color=fg+:11 --height 70% --reverse --select-1 --exit-0 --multi'

### above was in zshenv.
#########################

## brew
[ -f /opt/homebrew/bin/brew ] && eval $(/opt/homebrew/bin/brew shellenv)
[ -f /usr/local/bin/brew ] && eval $(/usr/local/bin/brew shellenv)

## go
[ -d $HOME/go ] && export GOPATH=$HOME/go

## guile
if type guile &>/dev/null; then
    export GUILE_LOAD_PATH="$HOMEBREW_PREFIX/share/guile/site/3.0"
    export GUILE_LOAD_COMPILED_PATH="$HOMEBREW_PREFIX/lib/guile/3.0/site-ccache"
    export GUILE_SYSTEM_EXTENSIONS_PATH="$HOMEBREW_PREFIX/lib/guile/3.0/extensions"
fi

## postgres
[ -d $HOMEBREW_PREFIX/var/postgres ] && \
    export PGDATA=$HOMEBREW_PREFIX/var/postgres

## openjdk
export JAVA_HOME=`/usr/libexec/java_home`
export CPPFLAGS="-I$JAVA_HOME/include"

## PATH, path is an array, PATH is a string.
typeset -U path
path=(
    $HOME/bin(N-/)
    $HOME/.local/bin(N-/)
    $HOME/.vim/plugged/vim-iced/bin(N-/)
    $JAVA_HOME/bin(N-/)
    $HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin(N-/)
    $HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin(N-/)
    $HOMEBREW_PREFIX/opt/lsof/bin(N-/)
    $HOMEBREW_PREFIX/opt/opencv/bin(N-)
    $HOMEBREW_PREFIX/opt/ruby/bin(N-/)
    $HOMEBREW_PREFIX/opt/sqlite/bin(N-/)
    $path)
export PATH

[ -f $HOME/.zsh_aliases ] && . $HOME/.zsh_aliases
