#!/bin/zsh
#
# being read from ~/.zprofile
#

## use gnu versions
[ -e $HOMEBREW_PREFIX/bin/gawk ]   && alias awk="$HOMEBREW_PREFIX/bin/gawk"
[ -e $HOMEBREW_PREFIX/bin/gcat ]   && alias cat="$HOMEBREW_PREFIX/bin/gcat"
[ -e $HOMEBREW_PREFIX/bin/gcp ]    && alias cp="$HOMEBREW_PREFIX/bin/gcp"
[ -e $HOMEBREW_PREFIX/bin/gegrep ] && alias egrep="$HOMEBREW_PREFIX/bin/gegrep --color=auto"
[ -e $HOMEBREW_PREFIX/bin/gfgrep ] && alias fgrep="$HOMEBREW_PREFIX/bin/gfgrep --color=auto"
[ -e $HOMEBREW_PREFIX/bin/ggrep ]  && alias grep="$HOMEBREW_PREFIX/bin/ggrep --color=auto"
[ -e $HOMEBREW_PREFIX/bin/gls ]    && alias ls="$HOMEBREW_PREFIX/bin/gls --color=auto"
[ -e $HOMEBREW_PREFIX/bin/gsed ]   && alias sed="$HOMEBREW_PREFIX/bin/gsed"
[ -e $HOMEBREW_PREFIX/bin/gsort ]  && alias sort="$HOMEBREW_PREFIX/bin/gsort"
[ -e $HOMEBREW_PREFIX/bin/gtar ]   && alias tar="$HOMEBREW_PREFIX/bin/gtar"

## shorten commands
alias al='ansible-playbook -i localhost, -c local'
alias df-h='df -h /System/Volumes/Data'
alias df-r='df -h /Volumes/RAM_DISK'
alias df-s='df -h /Volumes/SD?'
alias dl='docker ps -l -q'
alias grope='grep -r -I --exclude-dir=.git --exclude=\*~ --line-number'
alias inet='/sbin/ifconfig | grep "inet "'
alias l='ls -l'
alias la='ls -lA'
alias ll='ls -l | less -R'
alias llss='sudo tmutil listlocalsnapshots /'
alias ms='multipass shell'
alias pf="ps ax | grep '[s]sh -fN'"
alias pfw='pf'
alias psq='psql -h localhost -U postgres'
alias rm='trash-cli'
#alias tm='/System/Applications/Time\ Machine.app/Contents/MacOS/Time\ Machine'
alias today='date +%F'
#alias top='htop'

## tmux
alias ktx='ssh kafka -t /home/hkim/bin/tx'
alias otx='ssh orange -t /home/hkim/bin/tx'
alias ntx='ssh nuc.local -t /home/hkim/bin/tx'
alias ntx7='ssh nuc7.local -t /home/hkim/bin/tx'

## pi4 mathematica
alias mathematica-pi4='ssh -Y pi@pi4.local mathematica'
alias wolfram-pi4='ssh pi@pi4.local wolfram'

##############
# macos only #
##############

# Activity Monitor, 2020-09-20
alias am='/System/Applications/Utilities/Activity\ Monitor.app/Contents/MacOS/Activity\ Monitor 2>/dev/null'

alias ss='netstat -ptcp | grep ESTAB'
alias sqpro='/Applications/Sequel\ Pro.app/Contents/MacOS/Sequel\ Pro'
alias pgadmin='/Applications/pgAdmin\ 4.app/Contents/MacOS/pgAdmin4'

alias vnc-imac3='open vnc://imac3.local'
alias vnc-m2='open vnc://hkim.ddns.net'
alias vnc-m3='open vnc://10.0.34.5'
alias vnc-tmac2='open vnc://tmac2.local'

# macOS 12.3
alias python=python3
alias pip=pip3
#

## mount c104 AirMac Express
# does not work well. 2019-01-29
#alias mount-data='mount_smbfs smb://c104.melt.kyutech.ac.jp/Data /Volumes/Data'
