#!/bin/zsh
# origin: ${dotfiles}/zsh/zshenv
#
# zsh reads this first.
# next ~/.zprofile.
#

export G=/Users/hkim/projects/literacy/grading

# expires 2022-09-11
export GITHUB_API_TOKEN=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
export HOMEBREW_GITHUB_API_TOKEN=$GITHUB_API_TOKEN

export XDG_BASE_HOME=$HOME/.config

