#!/bin/zsh
#
# origin: ${dotfiles}/zsh/zshenv
#
# zsh read firstly this.
# if .zshenv_local exists, read it.
# then .zprofile
#
# order:
# > .zshenv
#   .zprofile
#   .zshrc
#   .zsh_aliase
#

# expires 2022-12-10
export GITHUB_API_TOKEN=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
export HOMEBREW_GITHUB_API_TOKEN=$GITHUB_API_TOKEN

export XDG_BASE_HOME=$HOME/.config

[ -f $HOME/.zshenv_local ] && . $HOME/.zshenv_local
